module4-task1
htmlacademy-react/1173965-six-cities-5 pull request #7
Opened 2020-10-26 21:09 UTC by knockyLoNe

2020-10-27 08:16 UTC, Fedos2589 requested changes

2020-10-27 08:16 UTC, Fedos2589 commented on src/mocks/offers.js
> +
много пустых строк)

2020-10-27 08:16 UTC, Fedos2589 commented on public/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
насколько я вижу по заданию, стили нужно было импортить не в весь бандл, а лишь в компонент карты
`После этого сможете импортировать (import) файл стилей leaflet.css прямо в компонент с картой.`
мне кажется паблик трогать не надо

2020-10-28 10:04 UTC, knockyLoNe commented on public/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
Так в задании написано, что можно или так или так:
Вот задание:
После подключения пакета leaflet вам необходимо его сконфигурировать. Начать следует с подключения CSS-стилей. Мы можем подключить стили непосредственно в index.html, а можем импортировать их прямо из JavaScript. Для этого потребуется установить в качестве dev-зависимостей последние версии пакетов style-loader и css-loader. А затем в файле конфигурации Webpack добавить поле module с ключом rules и опишите в последнем объект с правилами: (Ну и далее описание webpack)

2020-10-28 10:05 UTC, knockyLoNe commented on src/mocks/offers.js
> +
Пустые строки убрал

2020-10-28 11:11 UTC, merged