module5-task1
htmlacademy-react/1173965-six-cities-5 pull request #9
Opened 2020-11-05 17:33 UTC by knockyLoNe

2020-11-06 09:59 UTC, Fedos2589 requested changes

2020-11-06 09:59 UTC, Fedos2589 commented on src/store/action.js
> +  GET_PROPERTYS_LIST: `GET_PROPERTYS_LIST`,
properties

2020-11-06 09:59 UTC, Fedos2589 commented on src/store/reducer.js
> +      return Object.assign({}, cityId, state);
а не должен быть другой порядок? Object.assign({}, state, cityId);

2020-11-09 14:28 UTC, knockyLoNe commented on src/store/action.js
> +  GET_PROPERTYS_LIST: `GET_PROPERTYS_LIST`,
Исправлено

2020-11-09 14:28 UTC, knockyLoNe commented on src/store/reducer.js
> +      return Object.assign({}, cityId, state);
Наоборот сыпятся ошибки :)

2020-11-10 11:32 UTC, merged